### ISSUE TITLE
Flat stream delay option

### ISSUE THREAD

**Issue by nohm4n** [sistason/rtmp_stream_delayer#3]
Hi! 

I love the idea of this tool and would love to use it on my setup but I have no need for a backup stream and all that. I'd simply like to be able to add a stream delay at the nginx/rtmp level. Is there any optimization I can do to the Python scripts to just utilize that feature. Any help would be huge! Thanks!

**Comment by sistason** [comment]
You should be able to set SINGLE=True in the settings to just delay one stream and exit.

Sadly, my rtmp-streaming setup is long past and I cannot test this, for typos/validity. It should be fine, but with an hour of python-knowledge, you should be able to fix those. This script was written with not much more knowledge than that in the past ;)
